on: [push, pull_request]

name: Continuous integration

jobs:
  gdlint:
    name: Lint and Format checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install 'gdtoolkit==4.3.2'

      - name: Lint and Format Checks
        run: |
          ./check.sh

  benchmark:
    name: Performance Benchmark
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Godot Import
        run: godot --headless --import

      # TODO: run with the previous version and compare the results!
      - name: Benchmark
        run: |
          ./test.sh --benchmark-only

  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - run: './update_addons.sh'
    - name: Godot Import
      run: godot --headless --import
    - name: Gut Tests
      uses: jamie-pate/run-gut-tests-action@v2.0.3
      with:
        useContainer: false
        gutConfigPath: tests/.gutconfig.json


