on: [push, pull_request]

name: Continuous integration

jobs:
  gdlint:
    name: gdlint scripts
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Ensure python is installed
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install gdtoolkit
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install 'gdtoolkit==4.3.2'

      # Lint the godot-xr-tools addon
      - name: Lint and Format Checks
        run: |
          ./check.sh
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - run: './update_addons.sh'
    - name: Godot Import
      run: godot --headless --import
    - name: Gut Tests
      uses: jamie-pate/run-gut-tests-action@v2.0.3
      with:
        useContainer: false
        gutConfigPath: tests/.gutconfig.json


